version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:

  # s3-deploy:
  #   docker:
  #     - image: 'cimg/python:3.6'
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - aws-s3/sync:
  #         arguments: |
  #           --acl public-read \
  #           --cache-control "max-age=86400"
  #         aws-access-key-id: AWS_ACCESS_KEY
  #         aws-region: AWS_DEFAULT_REGION
  #         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  #         from: ./build/
  #         to: 's3://feedthemonster-development'
  
  s3-deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - attach_workspace:
          at: ~/project
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: ./lang/
          to: 's3://globallit-aws-s3-static-webapp-test-us-east-2/feed-the-monster-data'

  s3-deploy-prod:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - attach_workspace:
          at: ~/project
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY
          aws-region: AWS_PROD_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: ./build/
          to: 's3://feedthemonster-production'

# http://curious-reader-books-production.s3-website.ap-south-1.amazonaws.com/

workflows:
  s3-deploy-workflow:
    jobs:
      - s3-deploy:
          context:
            - aws-context
          filters:
            branches:
              only:
                - test
                - main
      # - s3-deploy-prod:
      #     requires:
      #       - npm-build
      #     filters:
      #       branches:
      #         only:
      #           - main
